# web: /src/support/builder_web.sh
postgres: /src/support/db/start.sh
api: /src/target/debug/bldr-api start --path /tmp/depot --config /config/config_api.toml
admin: /src/target/debug/bldr-admin start
router: /src/target/debug/bldr-router start
jobsrv: /src/target/debug/bldr-jobsrv start --config /config/config_jobsrv.toml
scheduler: /src/target/debug/bldr-scheduler start
sessionsrv: /src/target/debug/bldr-sessionsrv start --config /config/config_sessionsrv.toml
originsrv: /src/target/debug/bldr-originsrv start
worker: /src/target/debug/bldr-worker start --config /config/config_worker.toml
